site_fullname:          "KEG Engine"
site_name:              "KEG Engine.lv"
host:                   "KEG Engine.lv"
host_nice:              "KEG Engine.lv"
email_from:             "KEG Engine <keg_engine@keg_engine.lv>"
email:                  "keg_engine@keg_engine.lv"
rpp:                    20
locales:
  - lv
  - en

ga_account:             "UA-xxxxxxxx"